### ISSUE TITLE
CTRL-C for price lookup not working since Ulitimatum league

### ISSUE THREAD

**Issue by roerch** [und3rdg/xenontrade#18] opened 2021-04-18 15:37 UTC
Since the recent new league, the CTRL-C on an item to lookup its price is not working anymore. Using version 1.2.3 on debian testing, wmctrl installed, the new league is selected for price lookup and Price-check is enabled in settings.
All other features (Port to hideout, emergency exit, etc.) are working.

When pressing CTRL-C nothing happens in XenonTrade window. Copy/paste buffer contains text of the item, but I can't compare it to the previous league unfortunately. I paste as an example below the text of a unique item, which should trigger a lookup, but doesn't for me. Any help is appreciated, thanks.

```
Item Class: Belts
Rarity: Unique
Wurm's Molt
Leather Belt
--------
Requirements:
Level: 8
--------
Item Level: 11
--------
+27 to maximum Life (implicit)
--------
+22 to Strength
+21 to Intelligence
+18% to Cold Resistance
0.4% of Physical Attack Damage Leeched as Life
0.4% of Physical Attack Damage Leeched as Mana
--------
They say a lifetime of wisdom is carried
in every skin the great beasts shed.

```

**Comment by AdVurt** [comment] 2021-04-19 09:16
This is caused by the first line (in the example, "Item Class: Belts"). This line was added in Ultimatum league and the parser needs to take this into account.

**Comment by tewinget** [comment] 2021-04-20 03:18
> This is caused by the first line (in the example, "Item Class: Belts"). This line was added in Ultimatum league and the parser needs to take this into account.

I see the line in the parser that is checking for this; do you know if *every* item now starts with a line like "Item Class:" ?

If so it's a derp simple PR and I'll just make it real quick.

**Comment by roerch** [comment] 2021-04-20 07:06
Can't tell for **every** item, but the Items which are available to me show all these new first line, e.g.:
```
Item Class: Stackable Currency
Item Class: Divination Card
Item Class: Mana Flasks
Item Class: Active Skill Gems
Item Class: One Hand Maces
```
Would be surprised if they implement it just for a few subsets.

**Comment by AdVurt** [comment] 2021-04-20 08:59
> 
> 
> > This is caused by the first line (in the example, "Item Class: Belts"). This line was added in Ultimatum league and the parser needs to take this into account.
> 
> I see the line in the parser that is checking for this; do you know if _every_ item now starts with a line like "Item Class:" ?
> 
> If so it's a derp simple PR and I'll just make it real quick.

As per [the official patch notes](https://www.pathofexile.com/forum/view-thread/3079973), "Copying an item's description with Ctrl + C now also copies the Item Class."
I would imagine this is every item - I haven't confirmed it fully by analysing the clipboard but my Xenontrade isn't picking up any item and I've tried a lot of them.

**Comment by r-last** [comment] 2021-04-21 14:00
Its a bit of an inelegant hack but we can modify parser.js to amend the getClipboardLines function to remove the "Item Class :" line

`
  getClipboardLines() {
    if (this.clipboard.startsWith("Item Class: "))
    {
var resultarray = this.clipboard.split("\n");
resultarray.shift();
      return resultarray;
    }
    else
    {
      return this.clipboard.split("\n");
    }
  `}

**Comment by AdVurt** [comment] 2021-04-21 14:42
Being that most of the logic uses regexes to grab the relevant fields, I don't think that the inelegent hack is necessary. Having a glance through, I don't think there are many changes. I've spotted only four, they're all tiny, and they're all in parser.js.
Line 45 should become:
`        if (this.clipboard.startsWith("Item Class: ")) {`
Line 238 should become:
`        var index = 2;`
Line 242 should be:
`          index = 3;`
Line 291 should be:
`        var baseType = lines[3].replace(/[^0-9a-zA-ZäÄöÖüÜß\-, ']/gi, ""); // Replace newline garbage`

**Comment by r-last** [comment] 2021-04-21 17:27
@AdVurt Your solution is better. 

I had to add one extra change to get everything working. 
Line 111 became
`var value = match[2];`

I have tested this and it seems to be working for both rares and uniques.
I have created a pull request (#19) for it.

**Comment by undg** [comment] 2021-06-23 18:44
PR #19 is merged, so I'm closing the issue.

**Closed as completed by undg** 2021-06-23 18:44 UTC
